### ISSUE TITLE
Mysterious crash on first time running app

### ISSUE THREAD

**Issue by harlantwood** [willzeng/cograph#636]
I'm brand new to the project.  I believe I followed all readme instructions correctly.  When I issue:

`./bin/www`

I see: 

```
express-session deprecated undefined resave option; provide resave option app.coffee:66:11
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.coffee:66:11
```

Fine, just warnings.  My neo4j (also brand new) is running on http://localhost:7474/

When I visit http://localhost:3000/ there is no response in the browser.  In the server console window I now see:

`Error: [object Object]`

Ah, mystery.  Any clues I can give (or receive) to try to find the issue?

**Comment by willzeng** [comment]
Right those warnings aren't related to the crash.  The crash you're getting is happening with Neo4j Community 2.2.1, which it appears causes some breaking change from the 2.1 versions we have been using.

To get it running now, you should be able to use the Neo4j 2.1.8 that can be installed from: http://neo4j.com/download/other-releases/

Let me know if this works for you.

I'll update the README to include this and also change this issue to indicate the need to upgrade to support Neo4j 2.2 versions, especially since 2.3 seems to be on its way.

**Comment by harlantwood** [comment]
Thanks, I'll try that.

**Comment by harlantwood** [comment]
Yup, that fixed it, thanks :-)
